In [1]:
import pandas as pd
import pickle

In [2]:
df = pd.read_csv('PDFs_description.csv')

In [5]:
with open('NER_dict.pickle', 'rb') as handle:
    master_dict = pickle.load(handle)

In [6]:
for index, row in df.iterrows():
    if 'DEFE' not in str(row['id']):
        continue

    ners = master_dict[row['id']]
    ners_dict = dict(ners)
    if 'DURATION' in ners_dict:
#         print ners_dict['DURATION']
        df.loc[index, 'duration'] = ners_dict['DURATION']
        continue
df.columns = df.columns.str.strip()

In [7]:
df

,Captions,Class,Class_1,Class_2,Class_3,Class_4,Class_5,Class_6,Class_7,URL,...,location,date,lat,lon,named_entities,DATE,reported_at,sighted_at,description,duration
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"RAF, Turnhouse Road, Dolphington Cottages, Ing...",NaN,55.951581,-3.346941,"[(u'TITLE', u'river'), (u'CAUSE_OF_DEATH', u'f...",MAY,NaN,MAY,remarks.date zih?z>31j- sqn 0 af ops.. 1.copie...,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Time, Telegraph Road, Woodchurch, Wirral, Nort...",NaN,53.328708,-3.100154,"[(u'ORGANIZATION', u'Time'), (u'NUMBER', u'27,...",NaN,NaN,NaN,"description of object.(humber of obecta, size,...",NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'7'), (u'PERCENT', u'20 % 15W'),...",MAY,MAY,1835,remarks [nona ngzandd -.' a mm @515 m.. .. .. ...,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Bedfordshire, Church End Road, Haynes, Central...",NaN,52.064003,-0.411114,"[(u'ORGANIZATION', u'Yorkshire UFO Societi'), ...",28th September,28th September,23rd July,NaN,seven weeks
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'\\'), (u'NUMBER', u'_ _'), (u'N...",NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'MSNESTR'), (u'NUMBER', u'1'), (...",NaN,NaN,NaN,"description of object. (number of objeccs, siz...",NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Havana, South Parade, Monkseaton, North Tynesi...",NaN,55.043750,-1.442781,"[(u'NUMBER', u'01'), (u'NUMBER', u'\xa7'), (u'...",NaN,NaN,1539,"description of object.(number of objecfs, size...",NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"GE, Greyfriars Road, Castle, Cardiff, Wales, C...",NaN,51.483406,-3.177785,"[(u'MISC', u'K. NEARBY'), (u'TITLE', u'river')...",MAY,MAY,0138,"objects '.(telephone lines, high voltage.lines...",NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'1'), (u'ORGANIZATION', u'UKRACC...",NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Angle, Pembrokeshire, Wales, SA71 5AU, UK",NaN,51.684838,-5.091757,"[(u'STATE_OR_PROVINCE', u'AS 05'), (u'NUMBER',...",NaN,NaN,1311,"description of object.(fumber of objects, size...",NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"The Close, Norwich, Norfolk, East of England, ...",NaN,52.630896,1.302361,"[(u'NUMBER', u'1'), (u'TITLE', u'river'), (u'C...",'46,'46,Now,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'MONEY', u'gfi cents \xa7 cents i cents \xe...",NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'???'), (u'NUMBER', u'5'), (u'NU...",NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'~'), (u'NUMBER', u'1'), (u'NUMB...",NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'\\'), (u'PERCENT', u'137 %'), (...",NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u',1'), (u'NUMBER', u'1'), (u'NUM...",NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'PERCENT', u'Bud1 %'), (u'PERCENT', u'E %')]",NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'1012.09'), (u'NUMBER', u'0'), (...",NaN,NaN,NaN,"description of object.(number 0? objects, size...",NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'294'), (u'NUMBER', u'.33')]",NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'10 A. B. J.'), (u'NUMBER', u'05...",' 11MAY,' 11,0000,"description of object.(humbcr nf objects, 3.co...",mo
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"RAF, Turnhouse Road, Dolphington Cottages, Ing...",NaN,55.951581,-3.346941,"[(u'TITLE', u'river'), (u'CAUSE_OF_DEATH', u'f...",MAY,NaN,MAY,"objects..(telephone lines, high voltage.lines,...",NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"RAF, Turnhouse Road, Dolphington Cottages, Ing...",NaN,55.951581,-3.346941,"[(u'TITLE', u'river'), (u'CAUSE_OF_DEATH', u'f...",NaN,NaN,NaN,"objects ' .(telephone 11nes, high voltage.line...",NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'PERCENT', u'2 %'), (u'NUMBER', u'.1'), (u'...",NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'NUMBER', u'6'), (u'NUMBER', u'.25'), (u'NU...",NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"DST, 12, Choats Road, Scrattons Farm, Barking ...",NaN,51.521181,0.140202,"[(u'ORGANIZATION', u'DST'), (u'NUMBER', u'1'),...",NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'STATE_OR_PROVINCE', u'WV 5'), (u'NUMBER', ...",NaN,NaN,NaN,"description of object (number of objects, size...",A WK
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"[(u'MISC', u'B. F'), (u'NUMBER', u'.1'), (u'NU...",NaN,NaN,NaN,"objects/buildings etc.. ..1 q "" mm. ..to -._-....",NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Time, Telegraph Road, Woodchurch, Wirral, Nort...",NaN,53.328708,-3.100154,"[(u'NUMBER', u'1-5'), (u'NUMBER', u'```'), (u'...",14 Oct 84,9120,14 Oct 84,"description 01? object circular, no size..(hum...",10 minutes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3503,an airplane flying in the sky over a mountain .,"['parachute, chute']",parachute,chute,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3504,a group of people flying kites in the sky .,"['parachute, chute']",parachute,chute,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3505,a plane flying in the sky with a sky background,['nail'],nail,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3506,a man flying through the air while riding a sn...,['screw'],screw,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3507,a kite flying in the sky with a sky background,"['parachute, chute']",parachute,chute,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3508,a bird flying in the sky with a sky background,['vulture'],vulture,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3509,a man flying through the air while riding a sn...,"['grey whale, gray whale, devilfish, Eschricht...",grey whale,gray whale,devilfish,Eschrichtius gibbosus,Eschrichtius robustus,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3510,a person is in the air with a frisbee .,"['grey whale, gray whale, devilfish, Eschricht...",grey whale,gray whale,devilfish,Eschrichtius gibbosus,Eschrichtius robustus,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83461_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3511,a kite flying in the sky with a sky background,"['parachute, chute']",parachute,chute,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83460_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3512,a large jetliner flying through a cloudy blue ...,"['parachute, chute']",parachute,chute,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3513,a person flying a kite in a blue sky .,"['great white shark, white shark, man-eater, m...",great white shark,white shark,man-eater,man-eating shark,Carcharodon carcharias,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3514,a kite flying in the sky with a sky background,"['great white shark, white shark, man-eater, m...",great white shark,white shark,man-eater,man-eating shark,Carcharodon carcharias,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3515,a person flying a kite on the beach .,['jellyfish'],jellyfish,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3516,a black and white photo of a kite flying in th...,['jellyfish'],jellyfish,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3517,a blue and white plane flying over a body of w...,['jellyfish'],jellyfish,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83459_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3518,a large building with a clock on the front of ...,"['prison, prison house']",prison,prison house,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83456_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3519,a large building with a clock on the front of ...,"['prison, prison house']",prison,prison house,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83456_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3520,a large building with a large clock on it .,['boathouse'],boathouse,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83456_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3521,a fire hydrant in the snow near a tree .,"['spotlight, spot']",spotlight,spot,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83441_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3522,a giraffe standing in a field of tall grass .,['rapeseed'],rapeseed,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83438_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3523,a crowd of people standing around a store .,"['carousel, carrousel, merry-go-round, roundab...",carousel,carrousel,merry-go-round,roundabout,whirligig,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3524,a statue of a man and a woman holding a cake .,"['spotlight, spot']",spotlight,spot,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3525,a close up of a person holding a remote,['abaya'],abaya,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3526,a close up of a person holding a bowl of food,"['gong, tam-tam']",gong,tam-tam,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3527,a clock tower in the middle of a city .,"['cinema, movie theater, movie theatre, movie ...",cinema,movie theater,movie theatre,movie house,picture palace,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3528,a close up of a person holding a pair of scissors,"['nematode, nematode worm, roundworm']",nematode,nematode worm,roundworm,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3529,a person is holding a red apple,"['nematode, nematode worm, roundworm']",nematode,nematode worm,roundworm,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3530,a close up of a person holding a bird,"['nematode, nematode worm, roundworm']",nematode,nematode worm,roundworm,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83437_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3531,a view of a window from a window .,['guillotine'],guillotine,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83427_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3532,a person sitting at a desk with a laptop .,['guillotine'],guillotine,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mufoncms.com/files_jeud8334j/83427_...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.to_csv('PDFs_description.csv', index=False, encoding='utf-8')